<?php

namespace AppBundle\Repository;

/**
 * ApiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
