# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$aD1gV5gBOxkh82xC81RYLeOyGRP81draurMBEoCouzwo7iErPwVQW
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$XTx4D81Ca3WHxK0Jznsa.OYuYsUbRJnnVrsbiEecSIGTUTlNh3PL2
                        roles: 'ROLE_ADMIN'
        api_provider:
            entity:
                class: AppBundle:ApiUser
                property: apiKey
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: api_provider
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

            guard:
                authenticators:
                    - app.security.wxopen_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
