# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
#  wx_open_app_id: ''
#  wx_open_app_secret: ''

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.api_token_authenticator:
        class: AppBundle\Security\ApiTokenAuthenticator

    app.resource_owner.wxopen_client:
        class: AppBundle\ResourceOwner\WXOpenClient
        arguments: ['%wx_open_app_id%', '%wx_open_app_secret%', 'wx_open_callback']
